# .github/workflows/publish.yml
name: Broadcast new release

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: 'v'

# Publish using the reusable workflow from dart-lang.
jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update nylo.dev
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://nylo.dev/api/github/actions/nylo/version'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "X-GH-API-KEY": "${{ secrets.NYLO_API_GH_SECRET }}"}'
          data: '{"version": "${{ github.ref_name }}"}'